### ISSUE TITLE
Get a solution to counting to a number N recursively and adding the numbers

### ISSUE THREAD

**Issue by calvinsettachatgul** [calvinsettachatgul/cr#2]
assignment look the answer to count.js
// define a function
// inside the function you call the function
// add the numbers up from 1 to n done recursively instead of iteratively
// write unit tests for the function

**Comment by calvinsettachatgul** [comment]
pull request is here

**Comment by calvinsettachatgul** [comment]
@robinchoii did you get a chance to work on this?

**Comment by robinchoii** [comment]
oops i forgot to create the PR after pushing
