### ISSUE TITLE
get 4 examples for doing algorithms

### ISSUE THREAD

**Issue by calvinsettachatgul** [calvinsettachatgul/cr#6]
you can put them in the planning folder or planning readme
interview cake
hackerrank
codewars
leet code

**Comment by calvinsettachatgul** [comment]
@robinchoii Wanted to know if you found some problems to work on?

**Comment by robinchoii** [comment]
hey sorry, had a busy holiday week. ill add some by tonight

**Comment by robinchoii** [comment]
just added 3 problems

**Comment by calvinsettachatgul** [comment]
ok great thanks for that

**Comment by calvinsettachatgul** [comment]
closing this issue we have found 3 problems each
