### ISSUE TITLE
get solution for highest product of 3 numbers in an array

### ISSUE THREAD

**Issue by robinchoii** [calvinsettachatgul/cr#8]
lets start with problem and get a solution by next monday

**Comment by calvinsettachatgul** [comment]
great thanks! thank you for starting to use issues I think it help in
communication on getting things done on our list of tasks


Calvin Settachatgul
5102208405
[image: https://plus.google.com/u/0/103999096514768389080]
<https://t.sidekickopen72.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2BgPB-W4XXHPl64Jm-bW63RzZn56dLnTf3BCw1T02?t=https%3A%2F%2Fplus.google.com%2Fu%2F0%2F103999096514768389080&si=5292413445996544&pi=799e9bdc-f9dd-4474-8756-fcb93506cc63>
 [image: www.linkedin.com/in/calvinsettachatgul]
<https://t.sidekickopen72.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2BgPB-W4XXHPl64Jm-bW63RzZn56dLnTf3BCw1T02?t=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fcalvinsettachatgul&si=5292413445996544&pi=799e9bdc-f9dd-4474-8756-fcb93506cc63>
 [image: www.github.com/calvinsettachatgul]
<https://t.sidekickopen72.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2BgPB-W4XXHPl64Jm-bW63RzZn56dLnTf3BCw1T02?t=http%3A%2F%2Fwww.github.com%2Fcalvinsettachatgul&si=5292413445996544&pi=799e9bdc-f9dd-4474-8756-fcb93506cc63>
 [image: http://calvinsettachatgul.github.io/blog/skypeRedirect.html]
<https://t.sidekickopen72.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs2BgPB-W4XXHPl64Jm-bW63RzZn56dLnTf3BCw1T02?t=http%3A%2F%2Fcalvinsettachatgul.github.io%2Fblog%2FskypeRedirect.html&si=5292413445996544&pi=799e9bdc-f9dd-4474-8756-fcb93506cc63>

**Comment by calvinsettachatgul** [comment]
ok this was completed
